name: spinners
description: Spinners Flame game
version: 0.0.0
publish_to: none

environment:
  sdk: ^2.17.0
  flutter: ^2.10.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.1.0

flutter:
  assets: 
    - assets/images/
  uses-material-design: true
dev_dependencies:
  flutter_lints: ^2.0.1
